/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCareerPathwaysRouteImport } from './routes/_authenticated/career-pathways'
import { Route as AuthenticatedCertificationsRouteImport } from './routes/_authenticated/certifications'
import { Route as AuthenticatedClinicalRouteImport } from './routes/_authenticated/clinical'
import { Route as AuthenticatedClinicalExcellenceRouteImport } from './routes/_authenticated/clinical-excellence'
import { Route as AuthenticatedDigitalTwinRouteImport } from './routes/_authenticated/digital-twin'
import { Route as AuthenticatedDutySchedulingRouteImport } from './routes/_authenticated/duty-scheduling'
import { Route as AuthenticatedEbpRouteImport } from './routes/_authenticated/ebp'
import { Route as AuthenticatedEducationRouteImport } from './routes/_authenticated/education'
import { Route as AuthenticatedEscalationsRouteImport } from './routes/_authenticated/escalations'
import { Route as AuthenticatedExcellenceRouteImport } from './routes/_authenticated/excellence'
import { Route as AuthenticatedExecutiveRouteImport } from './routes/_authenticated/executive'
import { Route as AuthenticatedExecutiveIntelligenceRouteImport } from './routes/_authenticated/executive-intelligence'
import { Route as AuthenticatedFloatPoolRouteImport } from './routes/_authenticated/float-pool'
import { Route as AuthenticatedGrowthRouteImport } from './routes/_authenticated/growth'
import { Route as AuthenticatedGrowthPlansRouteImport } from './routes/_authenticated/growth-plans'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedLeaveManagementRouteImport } from './routes/_authenticated/leave-management'
import { Route as AuthenticatedNursingWorkforceIntelligenceRouteImport } from './routes/_authenticated/nursing-workforce-intelligence'
import { Route as AuthenticatedNursingWorkforceTwinRouteImport } from './routes/_authenticated/nursing-workforce-twin'
import { Route as AuthenticatedProcedureDocumentationRouteImport } from './routes/_authenticated/procedure-documentation'
import { Route as AuthenticatedProfessionalDevelopmentRouteImport } from './routes/_authenticated/professional-development'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedSchedulingRouteImport } from './routes/_authenticated/scheduling'
import { Route as AuthenticatedSkillsMatrixRouteImport } from './routes/_authenticated/skills-matrix'
import { Route as AuthenticatedUnitCapacityRouteImport } from './routes/_authenticated/unit-capacity'
import { Route as AuthenticatedWellbeingRouteImport } from './routes/_authenticated/wellbeing'
import { Route as AuthenticatedWorkflowIntelligenceRouteImport } from './routes/_authenticated/workflow-intelligence'
import { Route as AuthenticatedWorkforceRouteImport } from './routes/_authenticated/workforce'
import { Route as AuthenticatedWorkforceIntelligenceRouteImport } from './routes/_authenticated/workforce-intelligence'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedPatientPatientIdRouteImport } from './routes/_authenticated/patient.$patientId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareerPathwaysRoute =
  AuthenticatedCareerPathwaysRouteImport.update({
    id: '/career-pathways',
    path: '/career-pathways',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificationsRoute =
  AuthenticatedCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClinicalRoute = AuthenticatedClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClinicalExcellenceRoute =
  AuthenticatedClinicalExcellenceRouteImport.update({
    id: '/clinical-excellence',
    path: '/clinical-excellence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDigitalTwinRoute =
  AuthenticatedDigitalTwinRouteImport.update({
    id: '/digital-twin',
    path: '/digital-twin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDutySchedulingRoute =
  AuthenticatedDutySchedulingRouteImport.update({
    id: '/duty-scheduling',
    path: '/duty-scheduling',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEbpRoute = AuthenticatedEbpRouteImport.update({
  id: '/ebp',
  path: '/ebp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEducationRoute = AuthenticatedEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalationsRoute =
  AuthenticatedEscalationsRouteImport.update({
    id: '/escalations',
    path: '/escalations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExcellenceRoute = AuthenticatedExcellenceRouteImport.update({
  id: '/excellence',
  path: '/excellence',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutiveRoute = AuthenticatedExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutiveIntelligenceRoute =
  AuthenticatedExecutiveIntelligenceRouteImport.update({
    id: '/executive-intelligence',
    path: '/executive-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFloatPoolRoute = AuthenticatedFloatPoolRouteImport.update({
  id: '/float-pool',
  path: '/float-pool',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrowthRoute = AuthenticatedGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrowthPlansRoute =
  AuthenticatedGrowthPlansRouteImport.update({
    id: '/growth-plans',
    path: '/growth-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveManagementRoute =
  AuthenticatedLeaveManagementRouteImport.update({
    id: '/leave-management',
    path: '/leave-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNursingWorkforceIntelligenceRoute =
  AuthenticatedNursingWorkforceIntelligenceRouteImport.update({
    id: '/nursing-workforce-intelligence',
    path: '/nursing-workforce-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNursingWorkforceTwinRoute =
  AuthenticatedNursingWorkforceTwinRouteImport.update({
    id: '/nursing-workforce-twin',
    path: '/nursing-workforce-twin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcedureDocumentationRoute =
  AuthenticatedProcedureDocumentationRouteImport.update({
    id: '/procedure-documentation',
    path: '/procedure-documentation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalDevelopmentRoute =
  AuthenticatedProfessionalDevelopmentRouteImport.update({
    id: '/professional-development',
    path: '/professional-development',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulingRoute = AuthenticatedSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsMatrixRoute =
  AuthenticatedSkillsMatrixRouteImport.update({
    id: '/skills-matrix',
    path: '/skills-matrix',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnitCapacityRoute =
  AuthenticatedUnitCapacityRouteImport.update({
    id: '/unit-capacity',
    path: '/unit-capacity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWellbeingRoute = AuthenticatedWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowIntelligenceRoute =
  AuthenticatedWorkflowIntelligenceRouteImport.update({
    id: '/workflow-intelligence',
    path: '/workflow-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkforceRoute = AuthenticatedWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkforceIntelligenceRoute =
  AuthenticatedWorkforceIntelligenceRouteImport.update({
    id: '/workforce-intelligence',
    path: '/workforce-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPatientPatientIdRoute =
  AuthenticatedPatientPatientIdRouteImport.update({
    id: '/patient/$patientId',
    path: '/patient/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/career-pathways': typeof AuthenticatedCareerPathwaysRoute
  '/certifications': typeof AuthenticatedCertificationsRoute
  '/clinical': typeof AuthenticatedClinicalRoute
  '/clinical-excellence': typeof AuthenticatedClinicalExcellenceRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/duty-scheduling': typeof AuthenticatedDutySchedulingRoute
  '/ebp': typeof AuthenticatedEbpRoute
  '/education': typeof AuthenticatedEducationRoute
  '/escalations': typeof AuthenticatedEscalationsRoute
  '/excellence': typeof AuthenticatedExcellenceRoute
  '/executive': typeof AuthenticatedExecutiveRoute
  '/executive-intelligence': typeof AuthenticatedExecutiveIntelligenceRoute
  '/float-pool': typeof AuthenticatedFloatPoolRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/growth-plans': typeof AuthenticatedGrowthPlansRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/leave-management': typeof AuthenticatedLeaveManagementRoute
  '/nursing-workforce-intelligence': typeof AuthenticatedNursingWorkforceIntelligenceRoute
  '/nursing-workforce-twin': typeof AuthenticatedNursingWorkforceTwinRoute
  '/procedure-documentation': typeof AuthenticatedProcedureDocumentationRoute
  '/professional-development': typeof AuthenticatedProfessionalDevelopmentRoute
  '/research': typeof AuthenticatedResearchRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/skills-matrix': typeof AuthenticatedSkillsMatrixRoute
  '/unit-capacity': typeof AuthenticatedUnitCapacityRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/workflow-intelligence': typeof AuthenticatedWorkflowIntelligenceRoute
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/workforce-intelligence': typeof AuthenticatedWorkforceIntelligenceRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/career-pathways': typeof AuthenticatedCareerPathwaysRoute
  '/certifications': typeof AuthenticatedCertificationsRoute
  '/clinical': typeof AuthenticatedClinicalRoute
  '/clinical-excellence': typeof AuthenticatedClinicalExcellenceRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/duty-scheduling': typeof AuthenticatedDutySchedulingRoute
  '/ebp': typeof AuthenticatedEbpRoute
  '/education': typeof AuthenticatedEducationRoute
  '/escalations': typeof AuthenticatedEscalationsRoute
  '/excellence': typeof AuthenticatedExcellenceRoute
  '/executive': typeof AuthenticatedExecutiveRoute
  '/executive-intelligence': typeof AuthenticatedExecutiveIntelligenceRoute
  '/float-pool': typeof AuthenticatedFloatPoolRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/growth-plans': typeof AuthenticatedGrowthPlansRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/leave-management': typeof AuthenticatedLeaveManagementRoute
  '/nursing-workforce-intelligence': typeof AuthenticatedNursingWorkforceIntelligenceRoute
  '/nursing-workforce-twin': typeof AuthenticatedNursingWorkforceTwinRoute
  '/procedure-documentation': typeof AuthenticatedProcedureDocumentationRoute
  '/professional-development': typeof AuthenticatedProfessionalDevelopmentRoute
  '/research': typeof AuthenticatedResearchRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/skills-matrix': typeof AuthenticatedSkillsMatrixRoute
  '/unit-capacity': typeof AuthenticatedUnitCapacityRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/workflow-intelligence': typeof AuthenticatedWorkflowIntelligenceRoute
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/workforce-intelligence': typeof AuthenticatedWorkforceIntelligenceRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/': typeof AuthenticatedIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/career-pathways': typeof AuthenticatedCareerPathwaysRoute
  '/_authenticated/certifications': typeof AuthenticatedCertificationsRoute
  '/_authenticated/clinical': typeof AuthenticatedClinicalRoute
  '/_authenticated/clinical-excellence': typeof AuthenticatedClinicalExcellenceRoute
  '/_authenticated/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/_authenticated/duty-scheduling': typeof AuthenticatedDutySchedulingRoute
  '/_authenticated/ebp': typeof AuthenticatedEbpRoute
  '/_authenticated/education': typeof AuthenticatedEducationRoute
  '/_authenticated/escalations': typeof AuthenticatedEscalationsRoute
  '/_authenticated/excellence': typeof AuthenticatedExcellenceRoute
  '/_authenticated/executive': typeof AuthenticatedExecutiveRoute
  '/_authenticated/executive-intelligence': typeof AuthenticatedExecutiveIntelligenceRoute
  '/_authenticated/float-pool': typeof AuthenticatedFloatPoolRoute
  '/_authenticated/growth': typeof AuthenticatedGrowthRoute
  '/_authenticated/growth-plans': typeof AuthenticatedGrowthPlansRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/leave-management': typeof AuthenticatedLeaveManagementRoute
  '/_authenticated/nursing-workforce-intelligence': typeof AuthenticatedNursingWorkforceIntelligenceRoute
  '/_authenticated/nursing-workforce-twin': typeof AuthenticatedNursingWorkforceTwinRoute
  '/_authenticated/procedure-documentation': typeof AuthenticatedProcedureDocumentationRoute
  '/_authenticated/professional-development': typeof AuthenticatedProfessionalDevelopmentRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/scheduling': typeof AuthenticatedSchedulingRoute
  '/_authenticated/skills-matrix': typeof AuthenticatedSkillsMatrixRoute
  '/_authenticated/unit-capacity': typeof AuthenticatedUnitCapacityRoute
  '/_authenticated/wellbeing': typeof AuthenticatedWellbeingRoute
  '/_authenticated/workflow-intelligence': typeof AuthenticatedWorkflowIntelligenceRoute
  '/_authenticated/workforce': typeof AuthenticatedWorkforceRoute
  '/_authenticated/workforce-intelligence': typeof AuthenticatedWorkforceIntelligenceRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/career-pathways'
    | '/certifications'
    | '/clinical'
    | '/clinical-excellence'
    | '/digital-twin'
    | '/duty-scheduling'
    | '/ebp'
    | '/education'
    | '/escalations'
    | '/excellence'
    | '/executive'
    | '/executive-intelligence'
    | '/float-pool'
    | '/growth'
    | '/growth-plans'
    | '/learning'
    | '/leave-management'
    | '/nursing-workforce-intelligence'
    | '/nursing-workforce-twin'
    | '/procedure-documentation'
    | '/professional-development'
    | '/research'
    | '/scheduling'
    | '/skills-matrix'
    | '/unit-capacity'
    | '/wellbeing'
    | '/workflow-intelligence'
    | '/workforce'
    | '/workforce-intelligence'
    | '/workspace'
    | '/.mcp/invoke-tool/$tool'
    | '/patient/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/career-pathways'
    | '/certifications'
    | '/clinical'
    | '/clinical-excellence'
    | '/digital-twin'
    | '/duty-scheduling'
    | '/ebp'
    | '/education'
    | '/escalations'
    | '/excellence'
    | '/executive'
    | '/executive-intelligence'
    | '/float-pool'
    | '/growth'
    | '/growth-plans'
    | '/learning'
    | '/leave-management'
    | '/nursing-workforce-intelligence'
    | '/nursing-workforce-twin'
    | '/procedure-documentation'
    | '/professional-development'
    | '/research'
    | '/scheduling'
    | '/skills-matrix'
    | '/unit-capacity'
    | '/wellbeing'
    | '/workflow-intelligence'
    | '/workforce'
    | '/workforce-intelligence'
    | '/workspace'
    | '/'
    | '/.mcp/invoke-tool/$tool'
    | '/patient/$patientId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/career-pathways'
    | '/_authenticated/certifications'
    | '/_authenticated/clinical'
    | '/_authenticated/clinical-excellence'
    | '/_authenticated/digital-twin'
    | '/_authenticated/duty-scheduling'
    | '/_authenticated/ebp'
    | '/_authenticated/education'
    | '/_authenticated/escalations'
    | '/_authenticated/excellence'
    | '/_authenticated/executive'
    | '/_authenticated/executive-intelligence'
    | '/_authenticated/float-pool'
    | '/_authenticated/growth'
    | '/_authenticated/growth-plans'
    | '/_authenticated/learning'
    | '/_authenticated/leave-management'
    | '/_authenticated/nursing-workforce-intelligence'
    | '/_authenticated/nursing-workforce-twin'
    | '/_authenticated/procedure-documentation'
    | '/_authenticated/professional-development'
    | '/_authenticated/research'
    | '/_authenticated/scheduling'
    | '/_authenticated/skills-matrix'
    | '/_authenticated/unit-capacity'
    | '/_authenticated/wellbeing'
    | '/_authenticated/workflow-intelligence'
    | '/_authenticated/workforce'
    | '/_authenticated/workforce-intelligence'
    | '/_authenticated/workspace'
    | '/_authenticated/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/patient/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career-pathways': {
      id: '/_authenticated/career-pathways'
      path: '/career-pathways'
      fullPath: '/career-pathways'
      preLoaderRoute: typeof AuthenticatedCareerPathwaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certifications': {
      id: '/_authenticated/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof AuthenticatedCertificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinical': {
      id: '/_authenticated/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof AuthenticatedClinicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinical-excellence': {
      id: '/_authenticated/clinical-excellence'
      path: '/clinical-excellence'
      fullPath: '/clinical-excellence'
      preLoaderRoute: typeof AuthenticatedClinicalExcellenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digital-twin': {
      id: '/_authenticated/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AuthenticatedDigitalTwinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duty-scheduling': {
      id: '/_authenticated/duty-scheduling'
      path: '/duty-scheduling'
      fullPath: '/duty-scheduling'
      preLoaderRoute: typeof AuthenticatedDutySchedulingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebp': {
      id: '/_authenticated/ebp'
      path: '/ebp'
      fullPath: '/ebp'
      preLoaderRoute: typeof AuthenticatedEbpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education': {
      id: '/_authenticated/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AuthenticatedEducationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escalations': {
      id: '/_authenticated/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof AuthenticatedEscalationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/excellence': {
      id: '/_authenticated/excellence'
      path: '/excellence'
      fullPath: '/excellence'
      preLoaderRoute: typeof AuthenticatedExcellenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive': {
      id: '/_authenticated/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof AuthenticatedExecutiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive-intelligence': {
      id: '/_authenticated/executive-intelligence'
      path: '/executive-intelligence'
      fullPath: '/executive-intelligence'
      preLoaderRoute: typeof AuthenticatedExecutiveIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/float-pool': {
      id: '/_authenticated/float-pool'
      path: '/float-pool'
      fullPath: '/float-pool'
      preLoaderRoute: typeof AuthenticatedFloatPoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/growth': {
      id: '/_authenticated/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AuthenticatedGrowthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/growth-plans': {
      id: '/_authenticated/growth-plans'
      path: '/growth-plans'
      fullPath: '/growth-plans'
      preLoaderRoute: typeof AuthenticatedGrowthPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave-management': {
      id: '/_authenticated/leave-management'
      path: '/leave-management'
      fullPath: '/leave-management'
      preLoaderRoute: typeof AuthenticatedLeaveManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nursing-workforce-intelligence': {
      id: '/_authenticated/nursing-workforce-intelligence'
      path: '/nursing-workforce-intelligence'
      fullPath: '/nursing-workforce-intelligence'
      preLoaderRoute: typeof AuthenticatedNursingWorkforceIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nursing-workforce-twin': {
      id: '/_authenticated/nursing-workforce-twin'
      path: '/nursing-workforce-twin'
      fullPath: '/nursing-workforce-twin'
      preLoaderRoute: typeof AuthenticatedNursingWorkforceTwinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procedure-documentation': {
      id: '/_authenticated/procedure-documentation'
      path: '/procedure-documentation'
      fullPath: '/procedure-documentation'
      preLoaderRoute: typeof AuthenticatedProcedureDocumentationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional-development': {
      id: '/_authenticated/professional-development'
      path: '/professional-development'
      fullPath: '/professional-development'
      preLoaderRoute: typeof AuthenticatedProfessionalDevelopmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling': {
      id: '/_authenticated/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof AuthenticatedSchedulingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills-matrix': {
      id: '/_authenticated/skills-matrix'
      path: '/skills-matrix'
      fullPath: '/skills-matrix'
      preLoaderRoute: typeof AuthenticatedSkillsMatrixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unit-capacity': {
      id: '/_authenticated/unit-capacity'
      path: '/unit-capacity'
      fullPath: '/unit-capacity'
      preLoaderRoute: typeof AuthenticatedUnitCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wellbeing': {
      id: '/_authenticated/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof AuthenticatedWellbeingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflow-intelligence': {
      id: '/_authenticated/workflow-intelligence'
      path: '/workflow-intelligence'
      fullPath: '/workflow-intelligence'
      preLoaderRoute: typeof AuthenticatedWorkflowIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workforce': {
      id: '/_authenticated/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof AuthenticatedWorkforceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workforce-intelligence': {
      id: '/_authenticated/workforce-intelligence'
      path: '/workforce-intelligence'
      fullPath: '/workforce-intelligence'
      preLoaderRoute: typeof AuthenticatedWorkforceIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patient/$patientId': {
      id: '/_authenticated/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCareerPathwaysRoute: typeof AuthenticatedCareerPathwaysRoute
  AuthenticatedCertificationsRoute: typeof AuthenticatedCertificationsRoute
  AuthenticatedClinicalRoute: typeof AuthenticatedClinicalRoute
  AuthenticatedClinicalExcellenceRoute: typeof AuthenticatedClinicalExcellenceRoute
  AuthenticatedDigitalTwinRoute: typeof AuthenticatedDigitalTwinRoute
  AuthenticatedDutySchedulingRoute: typeof AuthenticatedDutySchedulingRoute
  AuthenticatedEbpRoute: typeof AuthenticatedEbpRoute
  AuthenticatedEducationRoute: typeof AuthenticatedEducationRoute
  AuthenticatedEscalationsRoute: typeof AuthenticatedEscalationsRoute
  AuthenticatedExcellenceRoute: typeof AuthenticatedExcellenceRoute
  AuthenticatedExecutiveRoute: typeof AuthenticatedExecutiveRoute
  AuthenticatedExecutiveIntelligenceRoute: typeof AuthenticatedExecutiveIntelligenceRoute
  AuthenticatedFloatPoolRoute: typeof AuthenticatedFloatPoolRoute
  AuthenticatedGrowthRoute: typeof AuthenticatedGrowthRoute
  AuthenticatedGrowthPlansRoute: typeof AuthenticatedGrowthPlansRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedLeaveManagementRoute: typeof AuthenticatedLeaveManagementRoute
  AuthenticatedNursingWorkforceIntelligenceRoute: typeof AuthenticatedNursingWorkforceIntelligenceRoute
  AuthenticatedNursingWorkforceTwinRoute: typeof AuthenticatedNursingWorkforceTwinRoute
  AuthenticatedProcedureDocumentationRoute: typeof AuthenticatedProcedureDocumentationRoute
  AuthenticatedProfessionalDevelopmentRoute: typeof AuthenticatedProfessionalDevelopmentRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedSchedulingRoute: typeof AuthenticatedSchedulingRoute
  AuthenticatedSkillsMatrixRoute: typeof AuthenticatedSkillsMatrixRoute
  AuthenticatedUnitCapacityRoute: typeof AuthenticatedUnitCapacityRoute
  AuthenticatedWellbeingRoute: typeof AuthenticatedWellbeingRoute
  AuthenticatedWorkflowIntelligenceRoute: typeof AuthenticatedWorkflowIntelligenceRoute
  AuthenticatedWorkforceRoute: typeof AuthenticatedWorkforceRoute
  AuthenticatedWorkforceIntelligenceRoute: typeof AuthenticatedWorkforceIntelligenceRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPatientPatientIdRoute: typeof AuthenticatedPatientPatientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCareerPathwaysRoute: AuthenticatedCareerPathwaysRoute,
  AuthenticatedCertificationsRoute: AuthenticatedCertificationsRoute,
  AuthenticatedClinicalRoute: AuthenticatedClinicalRoute,
  AuthenticatedClinicalExcellenceRoute: AuthenticatedClinicalExcellenceRoute,
  AuthenticatedDigitalTwinRoute: AuthenticatedDigitalTwinRoute,
  AuthenticatedDutySchedulingRoute: AuthenticatedDutySchedulingRoute,
  AuthenticatedEbpRoute: AuthenticatedEbpRoute,
  AuthenticatedEducationRoute: AuthenticatedEducationRoute,
  AuthenticatedEscalationsRoute: AuthenticatedEscalationsRoute,
  AuthenticatedExcellenceRoute: AuthenticatedExcellenceRoute,
  AuthenticatedExecutiveRoute: AuthenticatedExecutiveRoute,
  AuthenticatedExecutiveIntelligenceRoute:
    AuthenticatedExecutiveIntelligenceRoute,
  AuthenticatedFloatPoolRoute: AuthenticatedFloatPoolRoute,
  AuthenticatedGrowthRoute: AuthenticatedGrowthRoute,
  AuthenticatedGrowthPlansRoute: AuthenticatedGrowthPlansRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedLeaveManagementRoute: AuthenticatedLeaveManagementRoute,
  AuthenticatedNursingWorkforceIntelligenceRoute:
    AuthenticatedNursingWorkforceIntelligenceRoute,
  AuthenticatedNursingWorkforceTwinRoute:
    AuthenticatedNursingWorkforceTwinRoute,
  AuthenticatedProcedureDocumentationRoute:
    AuthenticatedProcedureDocumentationRoute,
  AuthenticatedProfessionalDevelopmentRoute:
    AuthenticatedProfessionalDevelopmentRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedSchedulingRoute: AuthenticatedSchedulingRoute,
  AuthenticatedSkillsMatrixRoute: AuthenticatedSkillsMatrixRoute,
  AuthenticatedUnitCapacityRoute: AuthenticatedUnitCapacityRoute,
  AuthenticatedWellbeingRoute: AuthenticatedWellbeingRoute,
  AuthenticatedWorkflowIntelligenceRoute:
    AuthenticatedWorkflowIntelligenceRoute,
  AuthenticatedWorkforceRoute: AuthenticatedWorkforceRoute,
  AuthenticatedWorkforceIntelligenceRoute:
    AuthenticatedWorkforceIntelligenceRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPatientPatientIdRoute: AuthenticatedPatientPatientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
