/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceIntelligenceRouteImport } from './routes/workforce-intelligence'
import { Route as WorkflowIntelligenceRouteImport } from './routes/workflow-intelligence'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProcedureDocumentationRouteImport } from './routes/procedure-documentation'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ExecutiveIntelligenceRouteImport } from './routes/executive-intelligence'
import { Route as EbpRouteImport } from './routes/ebp'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientPatientIdRouteImport } from './routes/patient.$patientId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const WorkforceIntelligenceRoute = WorkforceIntelligenceRouteImport.update({
  id: '/workforce-intelligence',
  path: '/workforce-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIntelligenceRoute = WorkflowIntelligenceRouteImport.update({
  id: '/workflow-intelligence',
  path: '/workflow-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedureDocumentationRoute = ProcedureDocumentationRouteImport.update({
  id: '/procedure-documentation',
  path: '/procedure-documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveIntelligenceRoute = ExecutiveIntelligenceRouteImport.update({
  id: '/executive-intelligence',
  path: '/executive-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const EbpRoute = EbpRouteImport.update({
  id: '/ebp',
  path: '/ebp',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPatientIdRoute = PatientPatientIdRouteImport.update({
  id: '/patient/$patientId',
  path: '/patient/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ebp': typeof EbpRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/procedure-documentation': typeof ProcedureDocumentationRoute
  '/research': typeof ResearchRoute
  '/workflow-intelligence': typeof WorkflowIntelligenceRoute
  '/workforce-intelligence': typeof WorkforceIntelligenceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ebp': typeof EbpRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/procedure-documentation': typeof ProcedureDocumentationRoute
  '/research': typeof ResearchRoute
  '/workflow-intelligence': typeof WorkflowIntelligenceRoute
  '/workforce-intelligence': typeof WorkforceIntelligenceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ebp': typeof EbpRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/procedure-documentation': typeof ProcedureDocumentationRoute
  '/research': typeof ResearchRoute
  '/workflow-intelligence': typeof WorkflowIntelligenceRoute
  '/workforce-intelligence': typeof WorkforceIntelligenceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/digital-twin'
    | '/ebp'
    | '/executive-intelligence'
    | '/learning'
    | '/login'
    | '/mcp'
    | '/procedure-documentation'
    | '/research'
    | '/workflow-intelligence'
    | '/workforce-intelligence'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/patient/$patientId'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/digital-twin'
    | '/ebp'
    | '/executive-intelligence'
    | '/learning'
    | '/login'
    | '/mcp'
    | '/procedure-documentation'
    | '/research'
    | '/workflow-intelligence'
    | '/workforce-intelligence'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/patient/$patientId'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/digital-twin'
    | '/ebp'
    | '/executive-intelligence'
    | '/learning'
    | '/login'
    | '/mcp'
    | '/procedure-documentation'
    | '/research'
    | '/workflow-intelligence'
    | '/workforce-intelligence'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/patient/$patientId'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EbpRoute: typeof EbpRoute
  ExecutiveIntelligenceRoute: typeof ExecutiveIntelligenceRoute
  LearningRoute: typeof LearningRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ProcedureDocumentationRoute: typeof ProcedureDocumentationRoute
  ResearchRoute: typeof ResearchRoute
  WorkflowIntelligenceRoute: typeof WorkflowIntelligenceRoute
  WorkforceIntelligenceRoute: typeof WorkforceIntelligenceRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PatientPatientIdRoute: typeof PatientPatientIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce-intelligence': {
      id: '/workforce-intelligence'
      path: '/workforce-intelligence'
      fullPath: '/workforce-intelligence'
      preLoaderRoute: typeof WorkforceIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-intelligence': {
      id: '/workflow-intelligence'
      path: '/workflow-intelligence'
      fullPath: '/workflow-intelligence'
      preLoaderRoute: typeof WorkflowIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedure-documentation': {
      id: '/procedure-documentation'
      path: '/procedure-documentation'
      fullPath: '/procedure-documentation'
      preLoaderRoute: typeof ProcedureDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-intelligence': {
      id: '/executive-intelligence'
      path: '/executive-intelligence'
      fullPath: '/executive-intelligence'
      preLoaderRoute: typeof ExecutiveIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebp': {
      id: '/ebp'
      path: '/ebp'
      fullPath: '/ebp'
      preLoaderRoute: typeof EbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$patientId': {
      id: '/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof PatientPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EbpRoute: EbpRoute,
  ExecutiveIntelligenceRoute: ExecutiveIntelligenceRoute,
  LearningRoute: LearningRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ProcedureDocumentationRoute: ProcedureDocumentationRoute,
  ResearchRoute: ResearchRoute,
  WorkflowIntelligenceRoute: WorkflowIntelligenceRoute,
  WorkforceIntelligenceRoute: WorkforceIntelligenceRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PatientPatientIdRoute: PatientPatientIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
